### ISSUE TITLE
Using ReactiveCrudRepository causes NoClassDefFoundError: org/springframework/transaction/reactive/TransactionSynchronization with the current BUILD SNAPSHOT

### ISSUE THREAD

**Issue by vinipuh5** [spring-projects/spring-data-r2dbc#113]
ReactiveCrudRepository API has stopped working since yesterday, it throws NoClassDefFoundError exception for TransactionSynchronization class. I tried to use the snapshot from May 6th and It worked fine. I'm using r2dbc-postgresql, build snapshot version.

Here is the call stack:
```
java.lang.NoClassDefFoundError: org/springframework/transaction/reactive/TransactionSynchronization
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.getConnection(DefaultDatabaseClient.java:189) ~[spring-data-r2dbc-1.0.0.BUILD-20190509.162539-66.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.inConnection(DefaultDatabaseClient.java:142) ~[spring-data-r2dbc-1.0.0.BUILD-20190509.162539-66.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.r2dbc.core.DefaultFetchSpec.rowsUpdated(DefaultFetchSpec.java:83) ~[spring-data-r2dbc-1.0.0.BUILD-20190509.162539-66.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.r2dbc.core.DefaultSqlResult.rowsUpdated(DefaultSqlResult.java:148) ~[spring-data-r2dbc-1.0.0.BUILD-20190509.162539-66.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.r2dbc.repository.support.SimpleR2dbcRepository.deleteById(SimpleR2dbcRepository.java:243) ~[spring-data-r2dbc-1.0.0.BUILD-20190509.162539-66.jar:1.0.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359) ~[spring-data-commons-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200) ~[spring-data-commons-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644) ~[spring-data-commons-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608) ~[spring-data-commons-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:99) ~[spring-data-commons-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at com.sun.proxy.$Proxy77.deleteById(Unknown Source) ~[?:?]
	at CALL OF deleteById FROM MY CODE```

**Comment by odrotbohm** [comment]
Spring Data R2DBC requires Spring Frameowkr 5.2 M2. You're using 5.1.

**Comment by mctdi** [comment]
I use 5.2.m3 and i have this error but i use java 8
