### ISSUE TITLE
Connection pool connection issue

### ISSUE THREAD

**Issue by Blquinn** [spring-projects/spring-data-r2dbc#150]
Hello, I've run into an issue during a preliminary benchmark where new connections to postgres seem to be timing out. Everything works fine under low load, but when I run a benchmark with `wrk -c 100 -d 20 'http://localhost:8080/users/ben'` I get intermittent 500 errors.

I'm on a macbook.

This is all of the code in one .kt file.

```kotlin
package me.blq.susp_test

import io.r2dbc.postgresql.PostgresqlConnectionConfiguration
import io.r2dbc.postgresql.PostgresqlConnectionFactory
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import kotlinx.coroutines.reactive.awaitFirstOrNull
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.data.annotation.Id
import org.springframework.data.r2dbc.function.DatabaseClient
import org.springframework.data.relational.core.mapping.Column
import org.springframework.data.relational.core.mapping.Table
import org.springframework.stereotype.Component
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RestController

@SpringBootApplication
class SuspTestApplication

fun main(args: Array<String>) {
    runApplication<SuspTestApplication>(*args)
}

@Configuration
class DBConfig {
    @Bean
    fun client(): DatabaseClient {
        val config = PostgresqlConnectionConfiguration.builder()
                .host("localhost")
                .database("susp_test")
                .username("postgres")
                .password("password").build()

        val connectionFactory = PostgresqlConnectionFactory(config)

        return DatabaseClient.create(connectionFactory)
    }
}

@Table("app_user")
class User(
        @Id
        @Column
        var id: Long,
        @Column
        var username: String
)

@Component
class UserRepository(private val db: DatabaseClient) {
    suspend fun getUserByUsername(username: String): User? {
        return db.execute().sql("select * from app_user where username = $1")
                .bind(0, username)
                .`as`(User::class.java)
                .fetch()
                .one()
                .awaitFirstOrNull()
    }
}

@RestController
@RequestMapping("/users")
class HelloController(private val userRepository: UserRepository) {
    @GetMapping("/{username}")
    suspend fun getUser(@PathVariable("username") username: String): User {
        return userRepository.getUserByUsername(username) ?: throw Exception("User $username not found!")
    }
}

```

I've tried removing the suspend funs and using Mono, but that ends up doing the same thing.

I'm getting the following stacktrace:

```
2019-07-18 17:22:41.066 ERROR 39740 --- [ctor-tcp-nio-64] a.w.r.e.AbstractErrorWebExceptionHandler : [687191e9] 500 Server Error for HTTP GET "/users/ben"

io.netty.channel.AbstractChannel$AnnotatedConnectException: Operation timed out: localhost/127.0.0.1:5432
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[na:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:670) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler me.blq.susp_test.HelloController#getUser(String, Continuation) [DispatcherHandler]
	|_ checkpoint ⇢ org.springframework.boot.web.reactive.filter.OrderedHiddenHttpMethodFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/users/ben" [ExceptionHandlingWebHandler]

Caused by: java.net.ConnectException: Operation timed out
	... 12 common frames omitted
```

`localhost/127.0.0.1:5432` is the address of my postgres, it's running native (not inside of docker or anything like that.

Also, I ran `watch 'psql -U postgres -c "SELECT sum(numbackends) FROM pg_stat_database;"'` to monitor the number of db connections and it seems to bounce around from 1-10 conns. It seems like postgres is registering the new connection just fine but netty is timing out the connection.

Thanks for any assistance!

**Comment by mp911de** [comment]
Seems you run out of connections in Postgres. Please use a connection pool such as R2DBC Pool, see https://github.com/r2dbc/r2dbc-pool.

**Comment by Blquinn** [comment]
Ah, okay, that definitely helped! No more 500s and much more reasonable performance.

Config now looks like:

```kotlin
@Configuration
class DBConfig {

    private var pool: ConnectionPool? = null

    @Bean
    fun pool(): ConnectionPool {
        val connectionFactory = ConnectionFactories.get(ConnectionFactoryOptions.builder()
                .option(ConnectionFactoryOptions.DRIVER, "pool")
                .option(ConnectionFactoryOptions.PROTOCOL, "postgresql")
                .option(ConnectionFactoryOptions.HOST, "localhost")
                .option(ConnectionFactoryOptions.PORT, 5432)
                .option(ConnectionFactoryOptions.USER, "postgres")
                .option(ConnectionFactoryOptions.PASSWORD, "password")
                .option(ConnectionFactoryOptions.DATABASE, "susp_test")
                .build())

        val configuration = ConnectionPoolConfiguration.builder(connectionFactory)
                .validationQuery("SELECT 1")
                .maxIdleTime(ofSeconds(2))
                .initialSize(2)
                .maxSize(20)
                .build()

        pool = ConnectionPool(configuration)
        return pool!!
    }

    @Bean
    fun client(pool: ConnectionPool): DatabaseClient {
        return DatabaseClient.create(pool)
    }

    @PreDestroy
    fun destroy() {
        pool?.let { if (it.isDisposed) it.dispose() }
    }
}
```

I'm having some issues getting the pool to use 20 connections using `io.r2dbc:r2dbc-pool:0.8.0.M8`. It just runs at a constant 10 conns. I'll probably open a ticket in the pool repo.

Thanks for the help though!

**Comment by mp911de** [comment]
Looking at https://github.com/r2dbc/r2dbc-pool/blob/master/src/main/java/io/r2dbc/pool/ConnectionPool.java#L120-L123, `maxSize` is propagated to the backing Reactor Pool. Let me investigate what happens.

**Comment by Blquinn** [comment]
Okay, thanks again. Would you like me to open a ticket?

**Comment by mp911de** [comment]
I just tried some simple code to test the pool behavior:

```java
AtomicLong counter = new AtomicLong();
DelegatingConnectionFactory dcf = new DelegatingConnectionFactory(H2TestSupport.createConnectionFactory()){

	@Override
	public Publisher<? extends Connection> create() {
		return Mono.from(super.create()).doOnNext(o -> {
			System.out.println(counter.incrementAndGet());
		});
	}
};

ConnectionPoolConfiguration config = ConnectionPoolConfiguration.builder(dcf)
		.maxSize(20).build();

ConnectionPool connectionPool = new ConnectionPool(config);

for (int i = 0; i < 20; i++) {
	Connection connection = connectionPool.create().block();
	System.out.println(connection);
}
```

The pool allocates properly up to 20 connections. Can you run the same code (you need to exchange the `ConnectionFactory` though) to verify it's working/not working for you?

I've tested against R2DBC Pool 0.8.0 M8 and latest snapshots.

**Comment by Blquinn** [comment]
Sure

I ran the following code:

```kotlin
    @Bean
    fun pool(): ConnectionPool {
        val connectionFactory = ConnectionFactories.get(ConnectionFactoryOptions.builder()
                .option(ConnectionFactoryOptions.DRIVER, "pool")
                .option(ConnectionFactoryOptions.PROTOCOL, "postgresql")
                .option(ConnectionFactoryOptions.HOST, "localhost")
                .option(ConnectionFactoryOptions.PORT, 5432)
                .option(ConnectionFactoryOptions.USER, "postgres")
                .option(ConnectionFactoryOptions.PASSWORD, "password")
                .option(ConnectionFactoryOptions.DATABASE, "susp_test")
                .build())

        val config = ConnectionPoolConfiguration.builder(connectionFactory)
                .maxSize(20).build()
        pool = ConnectionPool(config)
        for (i in 0..19) {
            val connection = pool!!.create().block()
            println("$i $connection")
        }
        return pool!!
```

Logs:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::             (v2.2.0.M4)

2019-07-20 12:25:45.787  INFO 64545 --- [           main] me.blq.susp_test.SuspTestApplicationKt   : Starting SuspTestApplicationKt on Bens-MacBook-Pro.local with PID 64545 (/Users/ben/Code/kotlin/susp_test/out/production/classes started by ben in /Users/ben/Code/kotlin/susp_test)
2019-07-20 12:25:45.789  INFO 64545 --- [           main] me.blq.susp_test.SuspTestApplicationKt   : No active profile set, falling back to default profiles: default
0 io.r2dbc.pool.PooledConnection@42c28305
1 io.r2dbc.pool.PooledConnection@2184b4f4
2 io.r2dbc.pool.PooledConnection@7d199c68
3 io.r2dbc.pool.PooledConnection@63411512
4 io.r2dbc.pool.PooledConnection@35cd68d4
5 io.r2dbc.pool.PooledConnection@316a598d
6 io.r2dbc.pool.PooledConnection@216914
7 io.r2dbc.pool.PooledConnection@6ba30587
8 io.r2dbc.pool.PooledConnection@35764bef
9 io.r2dbc.pool.PooledConnection@5633dafd
```

It stops at 10 conns.

**Comment by mp911de** [comment]
That is strange. Have you tried obtaining 20 connections directly from `val connectionFactory = ConnectionFactories.get(…)`? Please retry with [Reactor Pool 0.0.1.BUILD-SNAPSHOT](https://repo.spring.io/snapshot/io/projectreactor/addons/reactor-pool/0.0.1.BUILD-SNAPSHOT/reactor-pool-0.0.1.BUILD-20190712.135500-40.jar) and [R2DBC Pool 0.8.0.BUILD-SNAPSHOT](https://repo.spring.io/snapshot/io/r2dbc/r2dbc-pool/0.8.0.BUILD-SNAPSHOT/r2dbc-pool-0.8.0.BUILD-20190720.154452-25.jar).

**Comment by Blquinn** [comment]
I tried running connectionFactory.create() 20 times and having the same issue. I verified with a different lib that I can create 20 conns to the postgres instance as well. So it definitely appears to be related to the pool.

**Comment by lex-em** [comment]
I fixed it by creating connetction factory from postgres driver dirrectly 
```
        val connectionFactory = PostgresqlConnectionFactory(
                PostgresqlConnectionConfiguration.builder()
                        .host("localhost")
                        .port(5432)
                        .username("postgres")
                        .password("postgres")
                        .database("reactive_services")
                        .build())
```
