### ISSUE TITLE
Allow usage of Entity-level converters

### ISSUE THREAD

**Issue by cambierr** [spring-projects/spring-data-r2dbc#169]
Hi,

Using the latest build snapshots, I can not register custom converters without getting the error:

```
Caused by: org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class io.namespace.model.audit.Action!
	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:79) ~[spring-data-commons-2.2.0.RC1.jar:2.2.0.RC1]
	at org.springframework.data.r2dbc.repository.support.R2dbcRepositoryFactory.getEntityInformation(R2dbcRepositoryFactory.java:121) ~[spring-data-r2dbc-1.0.0.BUILD-20190823.043230-244.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.r2dbc.repository.support.R2dbcRepositoryFactory.getTargetRepository(R2dbcRepositoryFactory.java:92) ~[spring-data-r2dbc-1.0.0.BUILD-20190823.043230-244.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:302) ~[spring-data-commons-2.2.0.RC1.jar:2.2.0.RC1]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:297) ~[spring-data-commons-2.2.0.RC1.jar:2.2.0.RC1]
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:211) ~[spring-data-commons-2.2.0.RC1.jar:2.2.0.RC1]
	at org.springframework.data.util.Lazy.get(Lazy.java:94) ~[spring-data-commons-2.2.0.RC1.jar:2.2.0.RC1]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:300) ~[spring-data-commons-2.2.0.RC1.jar:2.2.0.RC1]
	at org.springframework.data.r2dbc.repository.support.R2dbcRepositoryFactoryBean.afterPropertiesSet(R2dbcRepositoryFactoryBean.java:116) ~[spring-data-r2dbc-1.0.0.BUILD-20190823.043230-244.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1850) ~[spring-beans-5.2.0.M3.jar:5.2.0.M3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1787) ~[spring-beans-5.2.0.M3.jar:5.2.0.M3]
	... 82 common frames omitted
```

here is my r2dbc config:
```java
@Configuration
public class R2dbcConfiguration extends AbstractR2dbcConfiguration {

    @Override
    public ConnectionFactory connectionFactory() {
        ...
    }

    @Override
    @Bean
    public R2dbcCustomConversions r2dbcCustomConversions() {
        List<Converter<?, ?>> converterList = new ArrayList<Converter<?, ?>>();
        converterList.add(new ActionToRowConverter());
        converterList.add(new RowToActionConverter());
        return new R2dbcCustomConversions(getStoreConversions(), converterList);
    }

    @WritingConverter
    public static class ActionToRowConverter implements Converter<Action, OutboundRow> {
        @Override
        public OutboundRow convert(Action source) {
            OutboundRow r = new OutboundRow();
            return r;
        }
    }

    @ReadingConverter
    public static class RowToActionConverter implements Converter<Row, Action> {
        @Override
        public Action convert(Row source) {
            return new Action();
        }
    }

}
```

my `Action` class being:

```java
@Table("audit.action")
@Getter
@Setter
@NoArgsConstructor
public class Action implements Model {

    @Id
    @Column("action_id")
    private UUID id;
...
}
```
and Model:
```java
public interface Model extends Persistable<UUID> {
}
```
Any idea or suggestion ?

**Comment by mp911de** [comment]
Registering a custom converter for a type considers that type entirely a simple type and does not register mapping metadata. We should fix that.

**Comment by mp911de** [comment]
Please note that converters need to adhere to your model because repositories use specific features (update by id, find by Id) that cannot be reflected through converters.

**Comment by mp911de** [comment]
That's in place now.

**Comment by cambierr** [comment]
thank you for the really quick fix!
