### ISSUE TITLE
IN CLAUSE and binding throws java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by santoror** [spring-projects/spring-data-r2dbc#178]
I'm tring to bind a parameter with an IN clause
```
@Query("SELECT * FROM docs where int_values IN (:status)")
Flux<Document> find(List<Integer> status);
```
I'm receiving the following exception
```
java.lang.IllegalArgumentException: Cannot encode [[7, 8, 10, 11]] parameter of type [java.util.Arrays$ArrayList]
	at io.r2dbc.mssql.codec.DefaultCodecs.encode(DefaultCodecs.java:103) ~[r2dbc-mssql-0.8.0.M8.jar:0.8.0.M8]
	at io.r2dbc.mssql.ParametrizedMssqlStatement.bind(ParametrizedMssqlStatement.java:207) ~[r2dbc-mssql-0.8.0.M8.jar:0.8.0.M8]
	at io.r2dbc.mssql.ParametrizedMssqlStatement.bind(ParametrizedMssqlStatement.java:220) ~[r2dbc-mssql-0.8.0.M8.jar:0.8.0.M8]
	at io.r2dbc.mssql.ParametrizedMssqlStatement.bind(ParametrizedMssqlStatement.java:56) ~[r2dbc-mssql-0.8.0.M8.jar:0.8.0.M8]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.lambda$bindByIndex$7(DefaultDatabaseClient.java:276) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_221]
```
I've also tried Integer[] and String but no luck.

Cross posting from https://github.com/r2dbc/r2dbc-mssql/issues/88

**Comment by mp911de** [comment]
That is an issue in Spring Data R2DBC how parameters are bound. We generally assume bind by index. Binding by index does not work with named parameter expansion as parameters are passed-thru to the `Statement` instead of being processed by named parameter expansion.

We need to properly bind values depending on whether the repository query uses named parameter expansion.

**Comment by adrian1388** [comment]
Sorry @mp911de, I don't understand how can I achieve this kind of binding (or is there any alternative?).
I want to use this query:
```(java)
@Query("SELECT * FROM Table WHERE foreignColumnId IN (:foreignIds)")
public Flux<Table> findByIds(List<UUID> foreignIds)
```
And a similar error comes:
```
java.lang.IllegalArgumentException: Cannot encode parameter of type java.util.ArrayList
	at io.r2dbc.postgresql.codec.DefaultCodecs.encode(DefaultCodecs.java:110) ~[r2dbc-postgresql-0.8.0.M8.jar:na]
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:83) ~[r2dbc-postgresql-0.8.0.M8.jar:na]
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:36) ~[r2dbc-postgresql-0.8.0.M8.jar:na]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.lambda$bindByIndex$9(DefaultDatabaseClient.java:296) ~[spring-data-r2dbc-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_172]
...
```
I will appreciate any help.

**Comment by mp911de** [comment]
That’s fixed in the latest snapshots.
