### ISSUE TITLE
database client dependency error

### ISSUE THREAD

**Issue by nikkisingh111333** [spring-projects/spring-data-r2dbc#179]
Description:

Field rr in GamOney2.GamOney2.H2controller required a bean named 'databaseClient' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean named 'databaseClient' in your configuration.
===========================================

Hello there,as i trying m working with new r2dbc release on my production project.
there are several things i need to ask about:
1.please solve this error as i m completely new in r2dbc world i m using project database configurations based on application.properties configuration(as described in docs) and updated almost every dependency based on r2dbc if im missing something please let me know.
2.is it safe to implement this api into my production app NOW ?. beacuse i really like the concept of "subscribers and publishers" way of data fetching/inserting .  
====================================================
HERES MY DEPENDENCIES
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.8.BUILD-SNAPSHOT</version>
		<relativePath/> 
	</parent>
	<groupId>GamOney-2</groupId>
	<artifactId>GamOney-2</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>GamOney-2</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Greenwich.BUILD-SNAPSHOT</spring-cloud.version>
		<vaadin.version>14.0.2</vaadin.version>
	</properties>

	<dependencies>
	

<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-client</artifactId>
    <version>1.0.0.M7</version>
</dependency>

<dependency>
    <groupId>tech.simter</groupId>
    <artifactId>simter-r2dbc-ext</artifactId>
    <version>1.3.0</version>
</dependency>

	
	<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-core</artifactId>
    <version>2.2.7</version>
</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-quartz</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-impl</artifactId>
    <version>2.0.1</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot.experimental</groupId>
    <artifactId>spring-boot-starter-data-r2dbc</artifactId>
    <version>0.1.0.M1</version>
  </dependency>
   <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-r2dbc</artifactId>
    <version>1.0.0.M2</version>
  </dependency>

  
<dependency>
    <groupId>org.springframework.boot.experimental</groupId>
    <artifactId>spring-boot-autoconfigure-r2dbc</artifactId>
    <version>0.1.0.M1</version>
</dependency>

<dependency>
    <groupId>org.springframework.boot.experimental</groupId>
    <artifactId>spring-boot-starter-data-r2dbc</artifactId>
    <version>0.1.0.M1</version>
</dependency>

<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-bom</artifactId>
    <version>Arabba-M8</version>
    <type>pom</type>
</dependency>

  
  <dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-postgresql</artifactId>
    <version>0.8.0.M8</version>
    <scope>runtime</scope>
  </dependency>
  
  
  <dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-pool</artifactId>
    <scope>runtime</scope>
  </dependency>
<dependency>
    <groupId>org.apache.tomcat</groupId>
    <artifactId>tomcat-jasper</artifactId>
    <version>9.0.17</version>
</dependency>

		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
			<version>1.2</version>
		</dependency>
		
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>jsp-api</artifactId>
    <version>2.0</version>
    <scope>provided</scope>
</dependency>
<dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.4</version>
    </dependency>
	<dependency>
			<groupId>org.apache.derby</groupId>
			<artifactId>derby</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-rest</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-quartz</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-proxy</artifactId>
    <version>1.0.0.M7</version>
</dependency>

 

<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-h2</artifactId>
    <version>0.8.0.M8</version>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-pool</artifactId>
    <version>0.8.0.M8</version>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-spi</artifactId>
    <version>0.8.0.M8</version>
</dependency>

<dependency>
    <groupId>com.google.code.findbugs</groupId>
    <artifactId>jsr305</artifactId>
    <version>3.0.2</version>
</dependency>

 
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>3.2.12.RELEASE</version>
</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-reactive</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.session</groupId>
			<artifactId>spring-session-core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>${vaadin.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
	 <repository>
        <id>spring-milestones</id>
        <name>Spring Milestones</name>
        <url>https://repo.spring.io/milestone</url>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
    <repository>
        <id>spring-snapshots</id>
        <name>Spring Snapshots</name>
        <url>https://repo.spring.io/snapshot</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
	    
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</repository>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</pluginRepository>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
	

</project>`

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by nikkisingh111333** [comment]
Okk I will send you code

**Comment by nikkisingh111333** [comment]
hey there i m getting  this error while starting and configuring springboot with r2bdc auto-configuration experimental:
Description:

Field rr in GamOney2.GamOney2.H2controller required a bean named 'databaseClient' that could not be found.

The injection point has the following annotations:
- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean named 'databaseClient' in your configuration.
here what i have:
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.8.BUILD-SNAPSHOT</version>
		<relativePath/> 
	</parent>
	<groupId>GamOney-2</groupId>
	<artifactId>GamOney-2</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>GamOney-2</name>
	<description>Demo project for Spring Boot</description>

<properties>
	<java.version>1.8</java.version>
	<spring-cloud.version>Greenwich.BUILD-SNAPSHOT</spring-cloud.version>
	<vaadin.version>14.0.2</vaadin.version>
</properties>

<dependencies>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-client</artifactId>
    <version>0.8.0.M8</version>
</dependency>
<dependency>
    <groupId>tech.simter</groupId>
    <artifactId>simter-r2dbc-ext</artifactId>
    <version>1.3.0</version>
</dependency>
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-core</artifactId>
    <version>2.2.7</version>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-quartz</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
</dependency>
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-impl</artifactId>
    <version>2.0.1</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot.experimental</groupId>
    <artifactId>spring-boot-starter-data-r2dbc</artifactId>
    <version>0.1.0.M1</version>
</dependency>
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-r2dbc</artifactId>
    <version>1.0.0.M2</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot.experimental</groupId>
    <artifactId>spring-boot-autoconfigure-r2dbc</artifactId>
    <version>0.1.0.M1</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot.experimental</groupId>
    <artifactId>spring-boot-actuator-autoconfigure-r2dbc</artifactId>
    <version>0.1.0.M1</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot.experimental</groupId>
    <artifactId>spring-boot-starter-data-r2dbc</artifactId>
    <version>0.1.0.M1</version>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-bom</artifactId>
    <version>Arabba-M8</version>
    <type>pom</type>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-spi-parent</artifactId>
    <version>1.0.0.M7</version>
    <type>pom</type>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-spi-test</artifactId>
    <version>1.0.0.M7</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-postgresql</artifactId>
    <version>1.0.0.M7</version>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-pool</artifactId>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>org.apache.tomcat</groupId>
    <artifactId>tomcat-jasper</artifactId>
    <version>9.0.17</version>
</dependency>
<dependency>
	<groupId>javax.servlet</groupId>
	<artifactId>jstl</artifactId>
	<version>1.2</version>
</dependency>
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>jsp-api</artifactId>
    <version>2.0</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.4</version>
</dependency>
<dependency>
	<groupId>org.apache.derby</groupId>
	<artifactId>derby</artifactId>
	<scope>runtime</scope>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-test</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-rest</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-mail</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-quartz</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-thymeleaf</artifactId>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-proxy</artifactId>
    <version>1.0.0.M7</version>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-h2</artifactId>
    <version>0.8.0.M8</version>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-pool</artifactId>
    <version>0.8.0.M8</version>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-spi</artifactId>
    <version>0.8.0.M8</version>
</dependency>
<dependency>
    <groupId>com.google.code.findbugs</groupId>
    <artifactId>jsr305</artifactId>
    <version>3.0.2</version>
</dependency>
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>3.2.12.RELEASE</version>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
</dependency>	
<dependency>
	<groupId>com.vaadin</groupId>
	<artifactId>vaadin-spring-boot-starter</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-reactive</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.session</groupId>
	<artifactId>spring-session-core</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-configuration-processor</artifactId>
	<optional>true</optional>
</dependency>
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
    <optional>true</optional>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-test</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>io.projectreactor</groupId>
	<artifactId>reactor-test</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-test-support</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>com.h2database</groupId>
	<artifactId>h2</artifactId>
	<scope>runtime</scope>
</dependency>
</dependencies>
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.r2dbc</groupId>
      <artifactId>r2dbc-bom</artifactId>
      <version>Arabba-M8</version>
      <type>pom</type>
      <scope>import</scope>
   </dependency>
   <dependency>
	  <groupId>org.springframework.cloud</groupId>
   	  <artifactId>spring-cloud-dependencies</artifactId>
	  <version>${spring-cloud.version}</version>
	  <type>pom</type>
	  <scope>import</scope>
   </dependency>
   <dependency>
		<groupId>com.vaadin</groupId>
		<artifactId>vaadin-bom</artifactId>
		<version>${vaadin.version}</version>
		<type>pom</type>
		<scope>import</scope>
   </dependency>
  </dependencies>
</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
	 <repository>
        <id>spring-milestones</id>
        <name>Spring Milestones</name>
        <url>https://repo.spring.io/milestone</url>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
    <repository>
        <id>spring-snapshots</id>
        <name>Spring Snapshots</name>
        <url>https://repo.spring.io/snapshot</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
	    <repository>
  <id>spring-milestones</id>
  <name>Spring Milestones</name>
  <url>https://repo.spring.io/milestone</url>
</repository>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</pluginRepository>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
	


</project>
==============================================================
heres my connectionfactory
`@Configuration
public class PostgresConnection extends AbstractR2dbcConfiguration{
  
//	@Bean
//	public DatabaseClient db() {
//		
//		return DatabaseClient.create(conn);
//	}

@Override
@Bean

public ConnectionFactory connectionFactory() {
	
	PostgresqlConnectionFactory h2c=new PostgresqlConnectionFactory(PostgresqlConnectionConfiguration.builder()
    		.schema("public")
    		.host("localhost")
    		.username("postgres")
    		.password("nikkibro0")  //Recative method chaining for PostgresSQL DB connection and configuration
    		.port(5432)
    		.database("postgres")
    		.build());
	R2dbcTransactionManager tm = new R2dbcTransactionManager(h2c);
	//TransactionalOperator rxtx = TransactionalOperator.create(tm);
	// ConnectionPool c=new ConnectionPool( ConnectionPoolConfiguration.builder(cf).maxAcquireTime(Duration.ofSeconds(1000)).initialSize(25).build());
	// TODO Auto-generated method stub
	return h2c;
}
	

}`
=================================================================
heres my properties (please tell me if im wrong here):
`server.port=8087
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.h2.console.settings.trace=true
#spring.r2dbc.url=r2dbc:h2:mem:///results?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.r2dbc.username=\u2026
#spring.r2dbc.password=\u2026
##spring.datasource.driver-class-name=io.r2dbc.h2.H2ConnectionFactoryProvider.H2_DRIVER
#spring.view.prefix:/WEB-INF/
#spring.view.suffix:.jsp
#spring.view.view-names:jsp/*
#spring.thymeleaf.view-names:thymeleaf-2/*
vaadin.compatibilityMode=true
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=nikkibro0
spring.r2dbc.name=mydatabase
spring.r2dbc.initialization-mode=always
spring.r2dbc.continue-on-error
spring.r2dbc.generate-unique-name=true`
========================================================
heres my table pojo and repository:
`package GamOney2.GamOney2;

import java.util.List;

import org.springframework.data.r2dbc.repository.R2dbcRepository;
import org.springframework.data.r2dbc.repository.query.Query;
import org.springframework.data.repository.reactive.ReactiveCrudRepository;
import org.springframework.stereotype.Repository;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@Repository
public interface ReactiveREPO extends R2dbcRepository<testdb2,Long>  {
  @Query(value="select * from testdb2 where name=$1")
  public Flux<testdb2> findit(String name);
  @Query(value="insert into testdb2(name,id) values($1,$2)")
  public Mono<testdb2> saveNew(String name,Long id);
}`
&
`package GamOney2.GamOney2;

import javax.annotation.Generated;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
@Builder
@Data
@Table("testdb2")
public class testdb2 {
  @Id
 // @GeneratedStrategy()
 public Long id;
 public String name;
public Long getId() {
	return id;
}

public String getName() {
	return name.strip();//strip() will remove all the white_spaces '_' from string and return it.
}
public void setId(Long id) {
	this.id=id;
}
public void setName(String name) {
	this.name=name;
}

  
  
}`
============================================================
and heres my controller:
`package GamOney2.GamOney2;

import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import org.reactivestreams.Publisher;
import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.data.r2dbc.function.DatabaseClient;
import org.springframework.data.r2dbc.repository.support.SimpleR2dbcRepository;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.data.r2dbc.core.DatabaseClient;
import org.springframework.data.r2dbc.core.TransactionalDatabaseClient;

import io.r2dbc.spi.Connection;
import io.r2dbc.spi.ConnectionFactory;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@RestController
public class H2controller {
	@Autowired
	ReactiveREPO rr;
	@Autowired
	ConnectionFactory conn;
	@Autowired
	H2repo hr;
	@Autowired
	DatabaseClient dc;
   @GetMapping(value="/Set",produces=MediaType.APPLICATION_JSON_VALUE)
   public Flux<testdb2> get(){
         my bussiness logics }`
this is all i have done so far and getting above error .
am i missing something.

**Comment by mp911de** [comment]
Please refrain from pasting all code into the comment. The pasted code is unusable that way. Instead, please attach a zip file. Thank you.

**Comment by nikkisingh111333** [comment]
[GamOney2Application - Copy.TXT](https://github.com/spring-projects/spring-data-r2dbc/files/3600328/GamOney2Application.-.Copy.TXT)
[H2connection - Copy.TXT](https://github.com/spring-projects/spring-data-r2dbc/files/3600329/H2connection.-.Copy.TXT)
[H2controller - Copy.txt](https://github.com/spring-projects/spring-data-r2dbc/files/3600330/H2controller.-.Copy.txt)
[PostgresConnection - Copy.TXT](https://github.com/spring-projects/spring-data-r2dbc/files/3600331/PostgresConnection.-.Copy.TXT)
[ReactiveREPO - Copy.TXT](https://github.com/spring-projects/spring-data-r2dbc/files/3600332/ReactiveREPO.-.Copy.TXT)
[testdb2 - Copy.TXT](https://github.com/spring-projects/spring-data-r2dbc/files/3600333/testdb2.-.Copy.TXT)
PLZ SEE ABOVE FILES.
HERES POM.XML

[pom.TXT](https://github.com/spring-projects/spring-data-r2dbc/files/3600345/pom.TXT)
AT LAST BUT MY APPLICATION.PROPERTIES WITH DATABASE CONFIGURATION 
`server.port=8087
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.h2.console.settings.trace=true
vaadin.compatibilityMode=true
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=nikkibro0
spring.r2dbc.name=mydatabase
spring.r2dbc.initialization-mode=always
spring.r2dbc.continue-on-error
spring.r2dbc.generate-unique-name=true`
=================================
ERROR REPORTING:
FIRST ERROR IS:
`Description:

Field rr in GamOney2.GamOney2.H2controller required a bean named 'databaseClient' that could not be found.

The injection point has the following annotations:
- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean named 'databaseClient' in your configuration.`
===============
SECOND ERROR IS:
`Caused by: java.lang.NoClassDefFoundError: org/springframework/transaction/reactive/AbstractReactiveTransactionManager
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	at GamOney2.GamOney2.PostgresConnection.connectionFactory(PostgresConnection.java:47) ~[classes/:na]
	at GamOney2.GamOney2.PostgresConnection$$EnhancerBySpringCGLIB$$6f178af0.CGLIB$connectionFactory$0(<generated>) ~[classes/:na]
	at GamOney2.GamOney2.PostgresConnection$$EnhancerBySpringCGLIB$$6f178af0$$FastClassBySpringCGLIB$$136d6d0b.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at GamOney2.GamOney2.PostgresConnection$$EnhancerBySpringCGLIB$$6f178af0.connectionFactory(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	... 146 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.transaction.reactive.AbstractReactiveTransactionManager`

**Comment by mp911de** [comment]
Thanks. 

Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

`Caused by: java.lang.NoClassDefFoundError: org/springframework/transaction/reactive/AbstractReactiveTransactionManager at` indicates that the used Spring Framework version isn't compatible with the one you're using. Please upgrade to Spring Framework 5.2 RC2 and Spring Data R2DBC 1.0.0.BUILD-SNAPSHOT.

**Comment by nikkisingh111333** [comment]
thanks for your reply you saved my another day.and what about "couldn't resolve databaseClient dependency error "as i've described above  as i have tried manually creating bean of databaseClient but didn't work. i think  r2dbc is not stable yet for production . Am i right? but i really loved the concept and wanna continue r2dbc as it grows.

**Comment by nikkisingh111333** [comment]
as far as i know i ve already ugraded my spring framework .all spring core,context,aop,and other stuffs are operating at 5.1.9 release and as you said i ve updated r2dbc to 1.0.0 build snapshot.but the classnotfound reactivetransaction is not found error is still there what can i do ? how can i upgrade so that i can get rid of it.

**Comment by nikkisingh111333** [comment]
as you describe upograding to springframework 5.2 RC2 i m unable to find it please specify where i can find it and use it. i have used spring r2dbc 1.0.0 M7 and it was working fine databaseclient was smooth but yesterday when i tried to enhanched r2dbc to 1.0.0 M2  with 0.8.0 M8 auto configuration accuator all started to messing up.
