### ISSUE TITLE
Cannot convert Clob to String in MappingR2dbcConverter

### ISSUE THREAD

**Issue by ddyycao** [spring-projects/spring-data-r2dbc#196]
I got this error when  select a text column and map it to a string field

```
db.execute("select name,alt_be from intel limit 1").asType<Intel>().fetch().one() // alt_be is a text column
```

```
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [dev.miku.r2dbc.mysql.codec.lob.SingletonClob] to type [java.lang.String]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321) ~[spring-core-5.2.0.RC2.jar:5.2.0.RC2]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:194) ~[spring-core-5.2.0.RC2.jar:5.2.0.RC2]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174) ~[spring-core-5.2.0.RC2.jar:5.2.0.RC2]
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter$RowParameterValueProvider.getParameterValue(MappingR2dbcConverter.java:486) ~[spring-data-r2dbc-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.relational.core.conversion.BasicRelationalConverter$ConvertingParameterValueProvider.getParameterValue(BasicRelationalConverter.java:256) ~[spring-data-relational-1.1.0.RC3.jar:1.1.0.RC3]
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.extractInvocationArguments(ClassGeneratingEntityInstantiator.java:250) ~[spring-data-commons-2.2.0.RC3.jar:2.2.0.RC3]
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.createInstance(ClassGeneratingEntityInstantiator.java:223) ~[spring-data-commons-2.2.0.RC3.jar:2.2.0.RC3]
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:84) ~[spring-data-commons-2.2.0.RC3.jar:2.2.0.RC3]
	at org.springframework.data.relational.core.conversion.BasicRelationalConverter.createInstance(BasicRelationalConverter.java:146) ~[spring-data-relational-1.1.0.RC3.jar:1.1.0.RC3]
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.createInstance(MappingR2dbcConverter.java:235) ~[spring-data-r2dbc-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
```

**Comment by mp911de** [comment]
`MappingR2dbcConverter` does not support mapping of `Clob`/`Blob` to scalar types (`String`, `byte[]`). Please try mapping yourself by providing a custom mapper or please use a `Clob` property.

To make `MappingR2dbcConverter` work with streaming data types, we require a few enhancements that allow streaming decoding of values. We also need a bit of design work first, to sketch out how this could work by using object mapping.

**Comment by maccamlcQ** [comment]
I have come across this problem with a tinytext column.

Is there an example of how to write a custom mapper, in the meantime?

**Comment by mp911de** [comment]
Call `DatabaseClient` with a mapping function like:

```java
databaseClient.execute("SELECT my_clob FROM table") //
		.map(row -> {
			return row.get("my_clob", String.class);
		})
```

or register a custom `Converter`. See the [documentation](https://docs.spring.io/spring-data/r2dbc/docs/1.0.0.RC1/reference/html/#mapping.explicit.converters) for further reference.

We're trying to address the issue in R2DBC SPI directly, see r2dbc/r2dbc-spi#130. Once that ticket is solved and drivers have caught up, the issue here will be solved.

**Comment by comcaptain** [comment]
@mp911de When using oracle r2dbc 0.2.0 (`group: 'com.oracle.database.r2dbc', name: 'oracle-r2dbc', version: '0.2.0'`), I got similar exceptoin:
```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [oracle.r2dbc.impl.OracleLargeObjects$2] to type [java.lang.String]
```

According to your comment above, I can write a custom converter for it. But I don't know how to convert a `io.r2dbc.spi.Clob` to `String`. I tried following converter but it makes the program stuck

```java
public class OracleClobConverter implements Converter<Clob, String>
{
	@Override public String convert(final Clob source)
	{
		return Mono.from(source.stream()).map(CharSequence::toString).block();
	}
}
```
