### ISSUE TITLE
Netty exception after switching to 0.8.0.RC1 of r2dbc-postgresql

### ISSUE THREAD

**Issue by otcyury** [spring-projects/spring-data-r2dbc#223]
I switched to using 0.8.0.RC1 of r2dbc-postgresql and started getting exception from Spring. Looks like the whole Netty Codec HTTP dependency got removed as a result. I switched to 0.8.0.RC1 because i need JSON support.

Relevant parts of my POM are below.

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.0.RELEASE</version>
		<relativePath/>
	</parent>

	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-webflux</artifactId>
	</dependency>

        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-postgresql</artifactId>
            <version>0.8.0.RC1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-r2dbc</artifactId>
            <version>1.0.0.M1</version>
        </dependency>

Exception stack is blow.

Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpHeaders
	at reactor.netty.http.client.HttpClient.<clinit>(HttpClient.java:963) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at org.springframework.http.client.reactive.ReactorClientHttpConnector.initHttpClient(ReactorClientHttpConnector.java:85) ~[spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.http.client.reactive.ReactorClientHttpConnector.<init>(ReactorClientHttpConnector.java:77) ~[spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.boot.autoconfigure.web.reactive.function.client.ClientHttpConnectorConfiguration$ReactorNetty.reactorClientHttpConnector(ClientHttpConnectorConfiguration.java:58) ~[spring-boot-autoconfigure-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 20 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpHeaders
	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.http.HttpHeaders
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_111]

**Comment by mp911de** [comment]
Please upgrade to R2DBC Postgres 0.8.0.RC2 as RC2 fixed the dependency issue.

**Comment by otcyury** [comment]
Thank you for the info. Looks like after change to RC2 I am facing new problem with dependencies. I had to also include spi dependency as below.

<dependency>
   <groupId>io.r2dbc</groupId>
   <artifactId>r2dbc-spi</artifactId>
    <version>0.8.0.M8</version>
</dependency>

Now I am getting following exception.

java.lang.NoSuchMethodError: io.r2dbc.spi.Row.get(ILjava/lang/Class;)Ljava/lang/Object;
	at io.r2dbc.postgresql.PostgresqlConnectionFactory.lambda$null$14(PostgresqlConnectionFactory.java:189) ~[r2dbc-postgresql-0.8.0.RC2.jar:0.8.0.RC2]
	at io.r2dbc.postgresql.PostgresqlResult.lambda$map$2(PostgresqlResult.java:96) ~[r2dbc-postgresql-0.8.0.RC2.jar:0.8.0.RC2]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:96) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:77) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]

**Comment by mp911de** [comment]
SPI must be 0.8 RC2, too.

**Comment by otcyury** [comment]
Got that fixed. Seeing issue in spring-data-r2dbc now. What version should I use for this dependency?

        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-r2dbc</artifactId>
            <version>1.0.0.M1</version>
        </dependency>

java.lang.NoSuchMethodError: io.r2dbc.spi.Row.get(Ljava/lang/Object;)Ljava/lang/Object;
	at org.springframework.data.r2dbc.function.convert.EntityRowMapper$RowParameterValueProvider.getParameterValue(EntityRowMapper.java:160) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.relational.core.conversion.BasicRelationalConverter$ConvertingParameterValueProvider.getParameterValue(BasicRelationalConverter.java:256) ~[spring-data-relational-1.1.0.RELEASE.jar:1.1.0.RELEASE]

**Comment by otcyury** [comment]
I changed this dependency to below and moved on to a next issue.

        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-r2dbc</artifactId>
            <version>1.0.0.M2</version>
        </dependency>

java.lang.NoSuchMethodError: org.springframework.transaction.reactive.TransactionSynchronizationManager.currentTransaction()Lreactor/core/publisher/Mono;
	at org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.doGetConnection(ConnectionFactoryUtils.java:88) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.getConnection(ConnectionFactoryUtils.java:70) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
