### ISSUE TITLE
save() entity with ID only throws NullPointerException

### ISSUE THREAD

**Issue by maresja1** [spring-projects/spring-data-r2dbc#250]
At around `DefaultDatabaseClient.java:1273`, list of columns that need to updated is made. In the case the entity has no other columns than ID, exception is thrown (callstack follows). I suppose, either nothing should happen (no columns to update) or different exception should be thrown.

```
java.lang.NullPointerException: null
	at org.springframework.data.r2dbc.core.DefaultStatementMapper.getMappedObject(DefaultStatementMapper.java:196) ~[spring-data-r2dbc-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.data.r2dbc.core.DefaultStatementMapper.getMappedObject(DefaultStatementMapper.java:186) ~[spring-data-r2dbc-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient$DefaultTypedUpdateSpec.exchange(DefaultDatabaseClient.java:1282) ~[spring-data-r2dbc-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient$DefaultTypedUpdateSpec.fetch(DefaultDatabaseClient.java:1252) ~[spring-data-r2dbc-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.data.r2dbc.repository.support.SimpleR2dbcRepository.save(SimpleR2dbcRepository.java:87) ~[spring-data-r2dbc-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:371) ~[spring-data-commons-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:204) ~[spring-data-commons-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:657) ~[spring-data-commons-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:621) ~[spring-data-commons-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605) ~[spring-data-commons-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at com.sun.proxy.$Proxy79.save(Unknown Source) ~[na:na]
```

**Comment by iguissouma** [comment]
I have same problem [stackoverflow](https://stackoverflow.com/questions/59126551/insert-contains-no-values-with-spring-data-r2dbc)

**Comment by mp911de** [comment]
Thanks for report. The `update(Object)` call should fail with `IllegalArgumentException: UPDATE contains no assignments` instead of `NullPointerException`.

`databaseClient.update().table(…).using(…)` derives the `WHERE` clause and the assignments from the class itself. So updating a single-column table isn't possible as we have only a single source for the primary key.

**Comment by iguissouma** [comment]
Adding a row in a table with a single column(IdOnly) is not possible too?

**Comment by mp911de** [comment]
It is possible if the ID is assigned as `insert().into(…).using(…)` translates to `INSERT INTO … (<fields>) VALUES(…)`.

**Comment by iguissouma** [comment]
I got an exception when trying to Insert

Code:

```
 val chatAdded = db.insert().into(ChatEntity::class.java)
                .using(ChatEntity(id = null))
                .map { row -> ChatEntity(id = row.get("id") as Int) }
                .awaitOne()
```

Exception:
```
java.lang.IllegalStateException: INSERT contains no values
	at org.springframework.data.r2dbc.core.DefaultStatementMapper.getMappedObject(DefaultStatementMapper.java:159) ~[spring-data-r2dbc-1.0.0.RC1.jar:1.0.0.RC1]
	at org.springframework.data.r2dbc.core.DefaultStatementMapper.getMappedObject(DefaultStatementMapper.java:144) ~[spring-data-r2dbc-1.0.0.RC1.jar:1.0.0.RC1]
```

**Comment by mp911de** [comment]
As mentioned, if the `id` value is assigned, it will work. `INSERT INTO chat_entity () VALUES();` isn't valid SQL. It can work on some databases (MySQL) but on others (SQL Server, Postgres) this kind of statement renders an error. Please, rather use `execute(…)` directly.
