### ISSUE TITLE
PostgreSQL's ssl=true property results in java.lang.ClassCastException

### ISSUE THREAD

**Issue by szpigielm** [spring-projects/spring-data-r2dbc#327]
Hi all,

When ssl=true property is included in postgresql URL, code results in:

```
Factory method 'connectionFactory' threw exception; nested exception is java.lang.ClassCastException: java.lang.String incompatible with java.lang.Boolean
```

The way to reproduce this is to create simple project spring boot version `2.3.0.M3` with following properties:

```
r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?ssl=true
    username: postgres
    password: password
```

more detailed exception:

```
Caused by: java.lang.ClassCastException: java.lang.String incompatible with java.lang.Boolean
	at io.r2dbc.postgresql.PostgresqlConnectionFactoryProvider.createConfiguration(PostgresqlConnectionFactoryProvider.java:171) ~[r2dbc-postgresql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.postgresql.PostgresqlConnectionFactoryProvider.create(PostgresqlConnectionFactoryProvider.java:121) ~[r2dbc-postgresql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.postgresql.PostgresqlConnectionFactoryProvider.create(PostgresqlConnectionFactoryProvider.java:42) ~[r2dbc-postgresql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.spi.ConnectionFactories.find(ConnectionFactories.java:112) ~[r2dbc-spi-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.spi.ConnectionFactories.get(ConnectionFactories.java:142) ~[r2dbc-spi-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryBuilder.build(ConnectionFactoryBuilder.java:125) ~[spring-boot-autoconfigure-2.3.0.M3.jar:2.3.0.M3]
	at org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryConfigurations.createConnectionFactory(ConnectionFactoryConfigurations.java:56) ~[spring-boot-autoconfigure-2.3.0.M3.jar:2.3.0.M3]
	at org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryConfigurations$Pool.connectionFactory(ConnectionFactoryConfigurations.java:68) ~[spring-boot-autoconfigure-2.3.0.M3.jar:2.3.0.M3]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 22 common frames omitted
```

**Comment by mp911de** [comment]
Please report this issue against the `r2dbc-postgres` project since we cannot move issues across github organizations. The driver should try to make sense out of a given property. Additionally, the documentation is wrong in the driver project. SSL support is enabled by using the `r2dbcs` scheme so your URL should rather be: `r2dbcs:postgresql://localhost:5432/postgres`.
