### ISSUE TITLE
Add support for derived delete query methods

### ISSUE THREAD

**Issue by asleson** [spring-projects/spring-data-r2dbc#341]
Spring Boot 2.3.0M4
Spring Data R2DBC 1.1.0RC1
r2dbc-postgresql 0.0.2.RELEASE

Using the above I created a `ReactiveCrudRespository` that looks like this:

```
interface MyDomainRepository extends ReactiveCrudRepository<MyDomain, Integer> {
    Mono<Void> deleteBySomeProperty(String someProperty)
}
```

It's a delete by something other than the property that is annotated with `@Id`.

Invoking the method fails with the following:

```
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class java.lang.Void!
	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:79)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.FluxHandleFuseable] :
	reactor.core.publisher.Flux.handle(Flux.java:5472)
	io.r2dbc.postgresql.PostgresqlResult.map(PostgresqlResult.java:96)
Error has been observed at the following site(s):
	|_     Flux.handle ⇢ at io.r2dbc.postgresql.PostgresqlResult.map(PostgresqlResult.java:96)
	|_    Flux.flatMap ⇢ at org.springframework.data.r2dbc.core.DefaultSqlResult$2.apply(DefaultSqlResult.java:80)
	|_  Flux.usingWhen ⇢ at org.springframework.data.r2dbc.core.DefaultDatabaseClient.inConnectionMany(DefaultDatabaseClient.java:192)
	|_ Flux.onErrorMap ⇢ at org.springframework.data.r2dbc.core.DefaultDatabaseClient.inConnectionMany(DefaultDatabaseClient.java:199)
	|_     Flux.buffer ⇢ at org.springframework.data.r2dbc.core.DefaultFetchSpec.one(DefaultFetchSpec.java:52)
	|_    Flux.flatMap ⇢ at org.springframework.data.r2dbc.core.DefaultFetchSpec.one(DefaultFetchSpec.java:53)
	|_       Flux.next ⇢ at org.springframework.data.r2dbc.core.DefaultFetchSpec.one(DefaultFetchSpec.java:65)
Stack trace:
		at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:79)
		at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.getRequiredPersistentEntity(MappingR2dbcConverter.java:600)
		at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.read(MappingR2dbcConverter.java:116)
```

I used `Mono<Void>` as the return type because the built in `deleteById` returns `Mono<Void>`.  I tried changing the return type to `Mono<MyDomain>` just to try and that failed as well.

If I add a query like this:

```
interface MyDomainRepository extends ReactiveCrudRepository<MyDomain, Integer> {
    @Query('delete from mydomain where someproperty = $1')
    Mono<Void> deleteBySomeProperty(String someProperty)
}
```

It works successfully.

**Comment by mp911de** [comment]
Modifying queries are not yet supported. Feel free to submit a pull request.

**Comment by m1ngyuan** [comment]
@mp911de  If the code is available, I will create a PR for it

**Comment by mp911de** [comment]
Feel free to do so. Looking at the referenced commit, we don't require that many permutations for tests since statement mapping is tested already in other tests.

**Comment by m1ngyuan** [comment]
A PR has been created for this issue #345

**Comment by mp911de** [comment]
Thanks a lot, that's merged now.
