### ISSUE TITLE
NullPointerException when inserting entity with read only fields

### ISSUE THREAD

**Issue by ljrmorgan** [spring-projects/spring-data-r2dbc#354]
I have an entity with a field annotated with`@ReadOnlyProperty`. When trying to save an entity of that type to my database I get a `NullPointerException`:
```
Suppressed: java.lang.NullPointerException
		at org.springframework.data.r2dbc.core.DefaultReactiveDataAccessStrategy.shouldConvertArrayValue(DefaultReactiveDataAccessStrategy.java:225)
		at org.springframework.data.r2dbc.core.DefaultReactiveDataAccessStrategy.getOutboundRow(DefaultReactiveDataAccessStrategy.java:209)
		at org.springframework.data.r2dbc.core.DefaultDatabaseClient$DefaultTypedInsertSpec.exchange(DefaultDatabaseClient.java:1171)
		at org.springframework.data.r2dbc.core.DefaultDatabaseClient$DefaultTypedInsertSpec.access$1300(DefaultDatabaseClient.java:1067)
		at org.springframework.data.r2dbc.core.DefaultDatabaseClient$DefaultTypedInsertSpec$1.lambda$first$1(DefaultDatabaseClient.java:1153)
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:151)
		... 85 more
```

The issue seems to be that the `MappingR2dbcConverter` _does_ correctly skip read only properties when writing properties to the `OutboundRow`, but `DefaultReactiveDataAccessStrategy#getOutboundRow` _does not_ skip read only properties when retrieving the `SettableValue`s from the `OutboundRow`.

**Comment by ljrmorgan** [comment]
I'm intending to open a PR shortly that addresses this

**Comment by ljrmorgan** [comment]
On further investigation the issue is specifically because the property is considered "collection like" (my field is a `byte[]`). `DefaultReactiveDataAccessStrategy#shouldConvertArrayValue` dereferences `value` even though in this case it is `null`. Non collection properties are not impacted because that method returns early if `property.isCollectionLike()` returns `true`

**Comment by mp911de** [comment]
Thanks a lot. The fix is merged.
