### ISSUE TITLE
PropertyReferenceException if path expression maps into simple type properties

### ISSUE THREAD

**Issue by murdos** [spring-projects/spring-data-r2dbc#369]
While working on the SpringBoot 2.3 support in JHipster, I stumble upon an new issue that we had not before:
```
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type java.lang.String!

	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:119)
	at org.springframework.data.mapping.context.PersistentPropertyPathFactory.getPair(PersistentPropertyPathFactory.java:237)
	at org.springframework.data.mapping.context.PersistentPropertyPathFactory.createPersistentPropertyPath(PersistentPropertyPathFactory.java:210)
	at org.springframework.data.mapping.context.PersistentPropertyPathFactory.lambda$getPersistentPropertyPath$2(PersistentPropertyPathFactory.java:183)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.springframework.data.mapping.context.PersistentPropertyPathFactory.getPersistentPropertyPath(PersistentPropertyPathFactory.java:182)
	at org.springframework.data.mapping.context.PersistentPropertyPathFactory.from(PersistentPropertyPathFactory.java:97)
	at org.springframework.data.mapping.context.PersistentPropertyPathFactory.from(PersistentPropertyPathFactory.java:110)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentPropertyPath(AbstractMappingContext.java:286)
```

I've created a minimal project to expose the issue: https://github.com/murdos/spring-data-r2dbc-mapping-bug

The issues seems to comes from the `password_hash` column of the `jhi_user` table: because `propertyPath` is then valued to `User.password.hash`.
It the column is renamed to `passwordhash` everything works fine.

**Comment by mp911de** [comment]
Thanks for reporting the issue. Spring Data's `PropertyPath` resolution tries to introspect the property `password` assuming that `hash` is a nested property of `password`. Therefore it attempts to introspect `String` which isn't an entity and so the mapping fails.

This issue pops up also in other Spring Data modules so we probably need to take a deeper look how to handle the issue.

**Comment by mp911de** [comment]
That's fixed now.
