### ISSUE TITLE
Result of derived ExistsBy Query not handled properly

### ISSUE THREAD

**Issue by pmaedel** [spring-projects/spring-data-r2dbc#468]
```sql
CREATE TABLE users
(
    id   bigserial primary key,
    user_name text unique
);
```

```kotlin
@Table("users")
data class User(
    @Id
    val id: Long? = null,
    val userName: String
)

interface UserRepository : CoroutineCrudRepository<User, Long> {

    suspend fun existsByUserName(userName: String): Boolean

    @Query("select exists (select 1 from users where user_name = :userName)")
    suspend fun customExistsByUserName(userName: String): Boolean
}
```
while `customExistsByUserName` works, `existsByUserName` will lead to an exception:
```
Failed to convert from type [io.r2dbc.postgresql.PostgresqlRow] to type [java.lang.Boolean] for value 'PostgresqlRow{context=ConnectionContext{client=io.r2dbc.postgresql.client.ReactorNettyClient@69980e91, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@62633db7, connection=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@69980e91, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@62633db7}, configuration=PostgresqlConnectionConfiguration{applicationName='r2dbc-postgresql', autodetectExtensions='true', connectTimeout=null, database='test', extensions=[], fetchSize=io.r2dbc.postgresql.PostgresqlConnectionConfiguration$Builder$$Lambda$808/0x0000000800664c40@7b13030d, forceBinary='false', host='localhost', loopResources='null', options='{}', password='********', port=32797, preferAttachedBuffers=false, socket=null, tcpKeepAlive=false, tcpNoDelay=false, username='postgres'}, portalNameSupplier=io.r2dbc.postgresql.DefaultPortalNameSupplier@1be9d0e7, statementCache=IndefiniteStatementCache{cache={INSERT INTO users (user_name) VALUES ($1) RETURNING *={[I@7d8d6c1a=MonoCacheTime}, SELECT users.id FROM users WHERE users.user_name = $1 LIMIT 1={[I@544819bc=MonoCacheTime}}, client=io.r2dbc.postgresql.client.ReactorNettyClient@69980e91, counter=2}}, columns=[Field{column=1, dataType=20, dataTypeModifier=-1, dataTypeSize=8, format=FORMAT_TEXT, name='id', table=16428}], isReleased=false}'; nested exception is java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Boolean
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [io.r2dbc.postgresql.PostgresqlRow] to type [java.lang.Boolean] for value 'PostgresqlRow{context=ConnectionContext{client=io.r2dbc.postgresql.client.ReactorNettyClient@69980e91, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@62633db7, connection=PostgresqlConnection{client=io.r2dbc.postgresql.client.ReactorNettyClient@69980e91, codecs=io.r2dbc.postgresql.codec.DefaultCodecs@62633db7}, configuration=PostgresqlConnectionConfiguration{applicationName='r2dbc-postgresql', autodetectExtensions='true', connectTimeout=null, database='test', extensions=[], fetchSize=io.r2dbc.postgresql.PostgresqlConnectionConfiguration$Builder$$Lambda$808/0x0000000800664c40@7b13030d, forceBinary='false', host='localhost', loopResources='null', options='{}', password='********', port=32797, preferAttachedBuffers=false, socket=null, tcpKeepAlive=false, tcpNoDelay=false, username='postgres'}, portalNameSupplier=io.r2dbc.postgresql.DefaultPortalNameSupplier@1be9d0e7, statementCache=IndefiniteStatementCache{cache={INSERT INTO users (user_name) VALUES ($1) RETURNING *={[I@7d8d6c1a=MonoCacheTime}, SELECT users.id FROM users WHERE users.user_name = $1 LIMIT 1={[I@544819bc=MonoCacheTime}}, client=io.r2dbc.postgresql.client.ReactorNettyClient@69980e91, counter=2}}, columns=[Field{column=1, dataType=20, dataTypeModifier=-1, dataTypeSize=8, format=FORMAT_TEXT, name='id', table=16428}], isReleased=false}'; nested exception is java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Boolean
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174)
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.read(MappingR2dbcConverter.java:113)
	at org.springframework.data.r2dbc.convert.EntityRowMapper.apply(EntityRowMapper.java:46)
	at org.springframework.data.r2dbc.convert.EntityRowMapper.apply(EntityRowMapper.java:29)
	at io.r2dbc.postgresql.PostgresqlResult.lambda$map$1(PostgresqlResult.java:113)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:96)
	at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:77)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:112)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onNext(FluxDiscardOnCancel.java:86)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
	at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:725)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:976)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:850)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:757)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:845)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:256)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:362)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:358)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Boolean
	at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:152)
	at io.r2dbc.postgresql.PostgresqlRow.decode(PostgresqlRow.java:90)
	at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:67)
	at org.springframework.data.r2dbc.convert.R2dbcConverters$RowToBooleanConverter.convert(R2dbcConverters.java:103)
	at org.springframework.data.r2dbc.convert.R2dbcConverters$RowToBooleanConverter.convert(R2dbcConverters.java:97)
	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:385)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
	... 49 more
```

**Comment by mp911de** [comment]
String-based queries via `@Query` do not support exists/count projections yet.

**Comment by pmaedel** [comment]
I think you misread, the @Query query works, but `suspend fun existsByUserName(userName: String): Boolean` does not

**Comment by mp911de** [comment]
You're right, my bad. I changed the title to reflect the issue.

**Comment by mp911de** [comment]
That's fixed now.
