### ISSUE TITLE
Enum values used through GenericExecuteSpec.bind not converted to String

### ISSUE THREAD

**Issue by Tienisto** [spring-projects/spring-data-r2dbc#484]
Similar to #465, when I use `GenericExecuteSpec.bind` I get an error.

Example:
```java
public enum CityEnum {
    PARIS,
    BERLIN,
    NEW_YORK
}

@Table("my_table")
public class MyEntity {

    @Id
    private Integer id;
    private CityEnum city;

    // getters and setters
}

@Repository
public class MyDatabaseClientRepo {

    private final DatabaseClient client;

    public MyDatabaseClientRepo(DatabaseClient client) {
        this.client = client;
    }

    // error
    public Mono<Void> findAll() {
        return client
                .sql("SELECT * FROM my_table WHERE city = :city")
                .bind("city", CityEnum.BERLIN)
                .then();
    }
}
```

```sql
CREATE TABLE my_table(
    id SERIAL PRIMARY KEY,
    city TEXT NOT NULL
);
```

Stacktrace:
```
java.lang.IllegalArgumentException: Cannot encode parameter of type com.example.demo.CityEnum
	at io.r2dbc.postgresql.codec.DefaultCodecs.encode(DefaultCodecs.java:165) ~[r2dbc-postgresql-0.8.5.RELEASE.jar:0.8.5.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.example.demo.MyController#getB() [DispatcherHandler]
	|_ checkpoint ⇢ HTTP GET "/b" [ExceptionHandlingWebHandler]
Stack trace:
		at io.r2dbc.postgresql.codec.DefaultCodecs.encode(DefaultCodecs.java:165) ~[r2dbc-postgresql-0.8.5.RELEASE.jar:0.8.5.RELEASE]
		at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:84) ~[r2dbc-postgresql-0.8.5.RELEASE.jar:0.8.5.RELEASE]
		at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:45) ~[r2dbc-postgresql-0.8.5.RELEASE.jar:0.8.5.RELEASE]
		at org.springframework.r2dbc.core.DefaultDatabaseClient$StatementWrapper.bind(DefaultDatabaseClient.java:551) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.binding.IndexedBindMarkers$IndexedBindMarker.bind(IndexedBindMarkers.java:86) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.NamedParameterUtils$ExpandedQuery.bind(NamedParameterUtils.java:555) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.NamedParameterUtils$ExpandedQuery.bindTo(NamedParameterUtils.java:618) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.DefaultDatabaseClient$DefaultGenericExecuteSpec.lambda$execute$2(DefaultDatabaseClient.java:363) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.DefaultDatabaseClient$DefaultGenericExecuteSpec.lambda$execute$3(DefaultDatabaseClient.java:380) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.DefaultDatabaseClient.sumRowsUpdated(DefaultDatabaseClient.java:200) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.DefaultDatabaseClient.access$000(DefaultDatabaseClient.java:65) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.DefaultDatabaseClient$DefaultGenericExecuteSpec.lambda$execute$4(DefaultDatabaseClient.java:388) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.ConnectionFunction.apply(ConnectionFunction.java:46) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.ConnectionFunction.apply(ConnectionFunction.java:31) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at org.springframework.r2dbc.core.DefaultDatabaseClient.lambda$inConnection$2(DefaultDatabaseClient.java:119) ~[spring-r2dbc-5.3.0-RC2.jar:5.3.0-RC2]
		at reactor.core.publisher.MonoUsingWhen.deriveMonoFromResource(MonoUsingWhen.java:114) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoUsingWhen.access$000(MonoUsingWhen.java:46) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoUsingWhen$ResourceSubscriber.onNext(MonoUsingWhen.java:183) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxRetry$RetrySubscriber.onNext(FluxRetry.java:86) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:148) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.pool.AbstractPool$Borrower.deliver(AbstractPool.java:415) ~[reactor-pool-0.2.0-RC2.jar:0.2.0-RC2]
		at reactor.pool.SimpleDequePool.lambda$drainLoop$15(SimpleDequePool.java:391) ~[reactor-pool-0.2.0-RC2.jar:0.2.0-RC2]
		at reactor.core.scheduler.ImmediateScheduler.schedule(ImmediateScheduler.java:51) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.pool.SimpleDequePool.drainLoop(SimpleDequePool.java:391) ~[reactor-pool-0.2.0-RC2.jar:0.2.0-RC2]
		at reactor.pool.SimpleDequePool.drain(SimpleDequePool.java:262) ~[reactor-pool-0.2.0-RC2.jar:0.2.0-RC2]
		at reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:257) ~[reactor-pool-0.2.0-RC2.jar:0.2.0-RC2]
		at reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:378) ~[reactor-pool-0.2.0-RC2.jar:0.2.0-RC2]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:137) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:137) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:170) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:170) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.pool.SimpleDequePool$QueueBorrowerMono.subscribe(SimpleDequePool.java:578) ~[reactor-pool-0.2.0-RC2.jar:0.2.0-RC2]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxRetry$RetrySubscriber.resubscribe(FluxRetry.java:116) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoRetry.subscribeOrReturn(MonoRetry.java:49) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Mono.subscribe(Mono.java:3972) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Operators.error(Operators.java:196) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Mono.subscribe(Mono.java:3987) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoUsingWhen.subscribe(MonoUsingWhen.java:96) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:305) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2346) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onSubscribe(MonoIgnoreThen.java:294) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:154) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:281) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:860) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2346) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2154) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2028) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Mono.subscribe(Mono.java:3987) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:448) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:218) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.Mono.subscribe(Mono.java:3987) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:173) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.0-RC2.jar:3.4.0-RC2]
		at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:580) ~[reactor-netty-http-1.0.0-RC2.jar:1.0.0-RC2]
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:594) ~[reactor-netty-core-1.0.0-RC2.jar:1.0.0-RC2]
		at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:446) ~[reactor-netty-core-1.0.0-RC2.jar:1.0.0-RC2]
		at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:497) ~[reactor-netty-http-1.0.0-RC2.jar:1.0.0-RC2]
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) ~[reactor-netty-core-1.0.0-RC2.jar:1.0.0-RC2]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:185) ~[reactor-netty-http-1.0.0-RC2.jar:1.0.0-RC2]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```

Version: Spring Boot 2.4-M4
Database: PostgreSQL

**Comment by mp911de** [comment]
That's expected behavior. You're using Spring R2DBC (`org.springframework.r2dbc.core`) which binds values as-is. Spring R2DBC behaves in that regard exactly like Spring JDBC that passes-thru all kinds of values. 

If you want to convert enum values to string, please call `Enum.name()`. 

Value conversions are Spring Data-specific. Invoking a repository query method or querying the database with `R2dbcEntityOperations` will apply conversion to binding values. 

The expectation to `DatabaseClient` to be a fully entity-aware utility stems probably from the fact, that Spring Data was a testbed for R2DBC before we cut things into slices that fit into Spring Framework and Spring Data.

**Comment by Tienisto** [comment]
Alright, thought it was a bug 👍
