### ISSUE TITLE
DatabaseClient cannot decode return type of RECORD

### ISSUE THREAD

**Issue by rgmz** [spring-projects/spring-data-r2dbc#605]
(Let me know if this would be more appropriate under a different repository.)

#### Information

* Spring Boot: `2.4.5`
* Dependencies:
    * `spring-boot-starter-data-r2dbc`
    * `r2dbc-postgresql`

#### Description

In certain cases, [returning arbitrary fields from a function](https://stackoverflow.com/a/6085167) is beneficial. Unfortunately, this doesn't seem possible with the `DatabaseClient`, as calling a function that returns a `RECORD` throws an exception:

```
java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object with OID 2249
        at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:155) ~[r2dbc-postgresql-0.8.7.RELEASE.jar:0.8.7.RELEASE]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
```

#### Details

Given the following function:

```sql
CREATE OR REPLACE FUNCTION record()
    RETURNS RECORD
    LANGUAGE plpgsql
AS
$$
DECLARE
    v_rec RECORD;
BEGIN
    SELECT 'foo', 'bar', 'baz'
    INTO v_rec;

    RETURN v_rec;
END;
$$;
```

When attempting to query it from our application, we receive an application:
```kotlin
val result = databaseClient.sql("SELECT record()")
    .fetch()
    .awaitOneOrNull()
log.info { "Result is: $result" }
```

<details>

<summary>Stack trace (click here to expand)</summary>

```
java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object with OID 2249
        at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:155) ~[r2dbc-postgresql-0.8.7.RELEASE.jar:0.8.7.RELEASE]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

Stack trace:
                at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:155) ~[r2dbc-postgresql-0.8.7.RELEASE.jar:0.8.7.RELEASE]
                at io.r2dbc.postgresql.PostgresqlRow.decode(PostgresqlRow.java:90) ~[r2dbc-postgresql-0.8.7.RELEASE.jar:0.8.7.RELEASE]
                at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:67) ~[r2dbc-postgresql-0.8.7.RELEASE.jar:0.8.7.RELEASE]
                at io.r2dbc.spi.Row.get(Row.java:51) ~[r2dbc-spi-0.8.4.RELEASE.jar:na]
                at org.springframework.r2dbc.core.ColumnMapRowMapper.getColumnValue(ColumnMapRowMapper.java:99) ~[spring-r2dbc-5.3.6.jar:5.3.6]
                at org.springframework.r2dbc.core.ColumnMapRowMapper.apply(ColumnMapRowMapper.java:63) ~[spring-r2dbc-5.3.6.jar:5.3.6]
                at org.springframework.r2dbc.core.ColumnMapRowMapper.apply(ColumnMapRowMapper.java:49) ~[spring-r2dbc-5.3.6.jar:5.3.6]
                at io.r2dbc.postgresql.PostgresqlResult.lambda$map$1(PostgresqlResult.java:111) ~[r2dbc-postgresql-0.8.7.RELEASE.jar:0.8.7.RELEASE]
                at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:169) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:667) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:745) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:787) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:265) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154) ~[reactor-core-3.4.5.jar:3.4.5]
                at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:735) ~[r2dbc-postgresql-0.8.7.RELEASE.jar:0.8.7.RELEASE]
                at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:986) ~[r2dbc-postgresql-0.8.7.RELEASE.jar:0.8.7.RELEASE]
                at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:860) ~[r2dbc-postgresql-0.8.7.RELEASE.jar:0.8.7.RELEASE]
                at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:767) ~[r2dbc-postgresql-0.8.7.RELEASE.jar:0.8.7.RELEASE]
                at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220) ~[reactor-core-3.4.5.jar:3.4.5]
                at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:280) ~[reactor-netty-core-1.0.6.jar:1.0.6]
                at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:389) ~[reactor-netty-core-1.0.6.jar:1.0.6]
                at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:401) ~[reactor-netty-core-1.0.6.jar:1.0.6]
                at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) ~[reactor-netty-core-1.0.6.jar:1.0.6]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
                at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```
</summary>

**Comment by mp911de** [comment]
This is a [R2DBC Driver issue](https://github.com/pgjdbc/r2dbc-postgresql/) as Spring isn't involved in binary protocol decoding. Out of interest, how does this work with PGJDBC? What does the JDBC driver return in such a case?
