### ISSUE TITLE
Problems with ReactiveCrudRepository methods like findByFieldFalse findByFieldTrue

### ISSUE THREAD

**Issue by kondratenko-yg** [spring-projects/spring-data-r2dbc#762]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/KONDRA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/KONDRA~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/KONDRA~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=RU link="#0563C1" vlink="#954F72" style='tab-interval:35.4pt'>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>Hello,<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>We got a
problem while moving from Spring Boot parent from 2.6.3 to 2.6.4.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>It is
moving from 1.4.1 to 1.4.2 for spring-data-r2dbc in spring-boot-starter-data-r2dbc.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>When we use
in our repository that extends ReactiveCrudRepository, methods with name like
findByFieldFalse or findByFieldTrue do not work, because parameter for field
bind with null.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>I have
example for illustrate it: <a
href="https://github.com/kondratenko-yg/reactive/tree/lib-from-parent">https://github.com/kondratenko-yg/reactive/tree/lib-from-parent</a><o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>TestRepository.findByHotTrue()
– is method like this.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>Logs, when call
<a href="http://localhost:8080/test">http://localhost:8080/test</a> (in spring-data-r2dbc
1.5.0 cannot see this log, only <span style='mso-spacerun:yes'> </span>1.4.2)<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>Executing
SQL statement [SELECT country.id, country.name, country.hot FROM country WHERE
country.hot = $1]<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>2022-06-07
13:30:29.128 DEBUG 16180 --- [ctor-http-nio-2]
io.r2dbc.h2.client.SessionClient<span style='mso-spacerun:yes'>        
</span>: Request:<span style='mso-spacerun:yes'>  </span>SELECT country.id,
country.name, country.hot FROM country WHERE country.hot = $1 {1: NULL}<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>I write
test TestServiceImplTest and results in table:<o:p></o:p></span></p>

  | Use spring-boot-starter-data-r2dbc | Version spring-boot-starter-parent | Version spring-data-r2dbc | Test
-- | -- | -- | -- | --
https://github.com/kondratenko-yg/reactive/tree/lib-1-4-1 | - | 2.6.4 | 1.4.1 | +
https://github.com/kondratenko-yg/reactive/tree/lib-1-4-2 | - | 2.6.4 | 1.4.2 | -
https://github.com/kondratenko-yg/reactive/tree/lib-from-parent | + | 2.6.4 | 1.4.2 | -
https://github.com/kondratenko-yg/reactive/tree/lib-1-4-3 | - | 2.6.4 | 1.4.3 | +
https://github.com/kondratenko-yg/reactive/tree/lib-1-4-4 | - | 2.6.4 | 1.4.4 | +
https://github.com/kondratenko-yg/reactive/tree/main | - | 2.6.4 | 1.5.0 | -

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>In our project:
Java 17 Spring Boot 2.6.4 postgresql (org.postgresql 42.3.3)<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>In Test
project: Java 17 Spring Boot 2.6.4 H2 (2.1.212)<o:p></o:p></span></p>

</body>

</html>

**Comment by kondratenko-yg** [comment]
I understand that problem with findFieldByFalse/True was solved in 1.4.3 [1.4.2...1.4.3](https://github.com/spring-projects/spring-data-r2dbc/compare/1.4.2...1.4.3) (src/main/java/org/springframework/data/r2dbc/query/QueryMapper.java) and close this issue.

There is NoClassDefFoundError in [test_project](https://github.com/kondratenko-yg/reactive/tree/main) for spring-data-r2dbc 1.5.0 . It is not problem with repository(findFieldByFalse/True). It is incompatibility with spring-boot-starter-parent 2.6.4, that have not org/springframework/data/convert/DtoInstantiatingConverter.


java.lang.NoClassDefFoundError: org/springframework/data/convert/DtoInstantiatingConverter
	at org.springframework.data.r2dbc.repository.query.R2dbcQueryExecution$ResultProcessingConverter.<init>(R2dbcQueryExecution.java:83) ~[spring-data-r2dbc-1.5.0.jar:1.5.0]
	at org.springframework.data.r2dbc.repository.query.AbstractR2dbcQuery.executeQuery(AbstractR2dbcQuery.java:107) ~[spring-data-r2dbc-1.5.0.jar:1.5.0]
	at org.springframework.data.r2dbc.repository.query.AbstractR2dbcQuery.lambda$execute$0(AbstractR2dbcQuery.java:88) ~[spring-data-r2dbc-1.5.0.jar:1.5.0]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152) ~[reactor-core-3.4.15.jar:3.4.15]
	at reactor.core.publisher.MonoFlatMapMany.subscribeOrReturn(MonoFlatMapMany.java:49) ~[reactor-core-3.4.15.jar:3.4.15]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8455) ~[reactor-core-3.4.15.jar:3.4.15]
	at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:94) ~[reactor-core-3.4.15.jar:3.4.15]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8469) ~[reactor-core-3.4.15.jar:3.4.15]
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.toVerifierAndSubscribe(DefaultStepVerifierBuilder.java:867) ~[reactor-test-3.4.15.jar:3.4.15]
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:823) ~[reactor-test-3.4.15.jar:3.4.15]
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:815) ~[reactor-test-3.4.15.jar:3.4.15]
	at com.nlmk.reactive.service.TestServiceImplTest.test(TestServiceImplTest.java:33) ~[test-classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
...
Caused by: java.lang.ClassNotFoundException: org.springframework.data.convert.DtoInstantiatingConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 81 common frames omitted

**Comment by kondratenko-yg** [comment]
I understand that problem with findFieldByFalse/True was solved in 1.4.3 [1.4.2...1.4.3](https://github.com/spring-projects/spring-data-r2dbc/compare/1.4.2...1.4.3) (src/main/java/org/springframework/data/r2dbc/query/QueryMapper.java) and close this issue.
