### ISSUE TITLE
Delete query with IN operater in Where-Clause fails due to BadSqlGrammarException

### ISSUE THREAD

**Issue by amx98** [spring-projects/spring-data-r2dbc#806]
1. Create a delete query with in operator in where clause. E.g

    ` @Modifying `
    ` @Query( `
    `     """`
    `         delete from user u `
     `        where u.user_id in (:userIds) `
     `    """ `
   `  ) `
   `  suspend fun deleteUsers(userIds: List<String>) `

2.  Execute calll deleteUsers with empty collection or list. E.g. 
`   repo.deleteUsers(emptyList()) `

Result: A bad BadSqlGrammarException occurs
Stack trace:
```
execute; bad SQL grammar [
            delete from user u
            where u.user_id in ()
        ]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42601] syntax error at or near ")"
org.springframework.r2dbc.BadSqlGrammarException: execute; bad SQL grammar [
            delete from article_category c
            where c.category_id in ()
        ]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42601] syntax error at or near ")"
	at app//org.springframework.r2dbc.connection.ConnectionFactoryUtils.convertR2dbcException(ConnectionFactoryUtils.java:235)
	at app//org.springframework.r2dbc.core.DefaultDatabaseClient.lambda$inConnection$4(DefaultDatabaseClient.java:125)
	at app//reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3762)
	at app//reactor.core.publisher.Mono.lambda$onErrorResume$32(Mono.java:3852)
	at app//reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at app//reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredError(MonoUsingWhen.java:277)
	at app//reactor.core.publisher.FluxUsingWhen$RollbackInner.onComplete(FluxUsingWhen.java:475)
	at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058)
	at app//reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at app//reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058)
	at app//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
	at app//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
	at app//reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:533)
	at app//reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:765)
	at app//reactor.core.publisher.Operators.complete(Operators.java:137)
	at app//reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at app//reactor.core.publisher.Mono.subscribe(Mono.java:4455)
	at app//reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:877)
	at app//reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at app//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
	at app//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at app//reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at app//reactor.core.publisher.Operators.complete(Operators.java:137)
	at app//reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at app//reactor.core.publisher.Mono.subscribe(Mono.java:4455)
	at app//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
	at app//reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
	at app//reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at app//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
	at app//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at app//reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
	at app//reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:236)
	at app//reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817)
	at app//reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:62)
	at app//reactor.core.publisher.Mono.subscribe(Mono.java:4455)
	at app//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
	at app//reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
	at app//reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at app//reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at app//reactor.core.publisher.Mono.subscribe(Mono.java:4455)
	at app//reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at app//reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:84)
	at app//reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
	at app//reactor.core.publisher.FluxFilter$FilterSubscriber.onError(FluxFilter.java:157)
	at app//reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onError(FluxFilter.java:291)
	at app//reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265)
	at app//reactor.core.publisher.Operators.error(Operators.java:198)
	at app//reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
	at app//reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
	at app//reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at app//reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at app//reactor.core.publisher.Mono.subscribe(Mono.java:4455)
	at app//reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onError(FluxUsingWhen.java:364)
	at app//reactor.core.publisher.MonoStreamCollector$StreamCollectorSubscriber.onError(MonoStreamCollector.java:150)
	at app//reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:842)
	at app//reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
	at app//reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
	at app//reactor.core.publisher.FluxFlatMap$FlatMapMain.innerError(FluxFlatMap.java:863)
	at app//reactor.core.publisher.FluxFlatMap$FlatMapInner.onError(FluxFlatMap.java:990)
	at app//reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onError(FluxHandleFuseable.java:226)
	at app//reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onError(MonoCollectList.java:114)
	at app//reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:198)
	at app//reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:668)
	at app//reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:746)
	at app//reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:788)
	at app//reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:239)
	at app//io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onNext(FluxDiscardOnCancel.java:91)
	at app//reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at app//reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:814)
	at app//reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:739)
	at app//reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:161)
	at app//io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:671)
	at app//io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:923)
	at app//io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:797)
	at app//io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:703)
	at app//reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126)
	at app//reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
	at app//reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
	at app//reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
	at app//reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:279)
	at app//reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:388)
	at app//reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404)
	at app//reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at app//io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at app//io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at app//io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at app//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at app//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at app//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at app//io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at app//io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)
Caused by: io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42601] syntax error at or near ")"
	at app//io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:96)
	at app//io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:65)
	at app//io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:132)
	at app//io.r2dbc.postgresql.PostgresqlResult.lambda$getRowsUpdated$0(PostgresqlResult.java:70)
	at app//reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:176)
	... 42 more
```

**Comment by mp911de** [comment]
This is the desired behavior if your database cannot handle empty `IN` lists. What else would be your expectation to happen?

**Comment by amx98** [comment]
I would have expected that an empty list would be converted to **null** or **empty blank value**.
E.g. `... where u.user_id in ('')` or `... where u.user_id in (null)'' `

**Comment by JoseLion** [comment]
An empty list can't convert to **empty blank value** because the left side of the IN-clause will not always be of character type. Also, it does not work the same as an "empty list" because it's always possible for `u.user_id` to have an empty value (`''`).

Converting to **null** looks like a good option at first, but it's problematic because the clause will evaluate to `NULL` instead of `FALSE`, which will break the behavior of a NOT-IN-clause:
```sql
SELECT 1 IN (NULL); -- returns NULL

SELECT 1 NOT IN (NULL); -- also returns NULL
```

The only workaround I've found so far is to use the `ARRAY` [overlap operator](https://www.postgresql.org/docs/current/functions-array.html) instead of the IN-clause. However, it requires explicit type casting, so the query becomes longer and harder to reason about:
```sql
DELETE FROM users u
WHERE
  array[u.user_id] && array[ :userIds ]::text[]; -- returns TRUE only when the two arrays overlap
```

**Important:** Notice the whitespaces between the square brackets and the parameter (`array[ :userIds ]`). Those are important, or you'll get an `InvalidDataAccessApiUsageException: No parameter specified for [userIds]]...` exception. I will open a separate issue for that later today 🙂

**Comment by JoseLion** [comment]
@mp911de, as you mentioned, PostgreSQL cannot handle empty lists. But also, not many databases allow this syntax because the spec does not allow that either (check [this thread](https://www.postgresql.org/message-id/21991.1162506863%40sss.pgh.pa.us) with Tom Lane, great info about this problem). So instead, would it be possible for Spring to normalize the `@Query` string before execution to replace empty lists with always true/false statements? It'd be very similar to what has been done for repository methods (#466).
```sql
IN () -- before
1 = 0 -- after

NOT IN () --before
1 = 1 -- after
```

**PS:** As the **spring-data-r2dbc** project was merged with **spring-data-relational**, I wonder if issues in this repo are still being tracked? I'll be happy to open a new ticket for this on **spring-data-relational** instead if necessary 🙂

**Comment by mp911de** [comment]
The named parameter support generally went into [Spring Framework](https://github.com/spring-projects/spring-framework/issues) entirely. We only replace `:named_parameter` with either a native bind marker or bind markers (if the parameter value is an array/collection). We do not rewrite the rest of the SQL statement.

Using `DatabaseClient` directly allows for some customization of the SQL statement, while `@Query` does not. You could create a wrapper for `DatabaseClient` to intercept our call to `sql(Supplier)` where we use the `PreparedOperation` to encapsulate SQL and binding parameters.

In any case, this project hosts only the issues for Spring Data R2DBC up to version 1.5. All newer versions are part of Spring Data Relational.
