### ISSUE TITLE
Could not read property java.math.BigDecimal 

### ISSUE THREAD

**Issue by hevan** [spring-projects/spring-data-r2dbc#85]
```
org.springframework.data.mapping.MappingException: Could not read property java.math.BigDecimal com.xp.ws.busi.domain.Customer.amount from result set!
        at org.springframework.data.r2dbc.function.convert.MappingR2dbcConverter.readFrom(MappingR2dbcConverter.java:144) ~[spring-data-r2dbc-1.0.0.gh-75-SNAPSHOT.jar!/:1.0.0.gh-75-SNAPSHOT]
        at org.springframework.data.r2dbc.function.convert.MappingR2dbcConverter.read(MappingR2dbcConverter.java:117) ~[spring-data-r2dbc-1.0.0.gh-75-SNAPSHOT.jar!/:1.0.0.gh-75-SNAPSHOT]
        at org.springframework.data.r2dbc.function.convert.MappingR2dbcConverter.read(MappingR2dbcConverter.java:101) ~[spring-data-r2dbc-1.0.0.gh-75-SNAPSHOT.jar!/:1.0.0.gh-75-SNAPSHOT]
        at org.springframework.data.r2dbc.function.convert.MappingR2dbcConverter.read(MappingR2dbcConverter.java:59) ~[spring-data-r2dbc-1.0.0.gh-75-SNAPSHOT.jar!/:1.0.0.gh-75-SNAPSHOT]
        at org.springframework.data.r2dbc.function.convert.EntityRowMapper.apply(EntityRowMapper.java:46) ~[spring-data-r2dbc-1.0.0.gh-75-SNAPSHOT.jar!/:1.0.0.gh-75-SNAPSHOT]
        at org.springframework.data.r2dbc.function.convert.EntityRowMapper.apply(EntityRowMapper.java:29) ~[spring-data-r2dbc-1.0.0.gh-75-SNAPSHOT.jar!/:1.0.0.gh-75-SNAPSHOT]
```

**Comment by mp911de** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). Please make sure to include the full stack trace, in the original description, not just the truncated one.

**Comment by hevan** [comment]
Use Mysql 8.0
