### ISSUE TITLE
Accessing inherited @Id property fails

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-r2dbc#87]
```java
@Getter
@Setter
@NoArgsConstructor
public class GenericEntity {
    @Id
    private Long id;

    @CreatedBy
    private Long createdBy;

    @CreatedDate
    private Long createdDate;

    @LastModifiedBy
    private Long updatedBy;

    @LastModifiedDate
    private Long updatedDate;

    @Version
    private Integer version = 0;
}

@Getter
@Setter
@NoArgsConstructor
public class Role extends GenericEntity {
    private String name;
    private String desc;
    private Integer sort;
}
```

Saving fails with:

```
java.lang.IllegalStateException: Required identifier property not found for class org.sky.entity.system.Role!
    at org.springframework.data.mapping.PersistentEntity.getRequiredIdProperty(PersistentEntity.java:105) ~[spring-data-commons-2.2.0.M2.jar:2.2.0.M2]
    at org.springframework.data.r2dbc.function.convert.MappingR2dbcConverter.lambda$populateIdIfNecessary$0(MappingR2dbcConverter.java:85) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
```

See https://stackoverflow.com/questions/55446827/are-there-mappedsuperclass-in-spring-reactive-data-r2dbc

**Comment by roboticscm** [comment]
It's not a bug, just remove @Version, it will work fine
