### ISSUE TITLE
H2Statement does not define or inherit an implementation of  bind(Ljava/lang/Integer;Ljava/lang/Object;)

### ISSUE THREAD

**Issue by eiswind** [spring-projects/spring-data-r2dbc#9]
I really don't know if this is a bug of r2dbc but it happens with spring data  when I try to save a very simple instance:

`
java.lang.AbstractMethodError: Receiver class io.r2dbc.h2.H2Statement does not define or inherit an implementation of the resolved method abstract bind(Ljava/lang/Integer;Ljava/lang/Object;)Lio/r2dbc/spi/Statement; of interface io.r2dbc.spi.Statement.
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient$DefaultTypedInsertSpec.lambda$exchange$4(DefaultDatabaseClient.java:992) ~[spring-data-r2dbc-1.0.0.BUILD-20181030.065337-2.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient$DefaultTypedInsertSpec.lambda$exchange$5(DefaultDatabaseClient.java:1002) ~[spring-data-r2dbc-1.0.0.BUILD-20181030.065337-2.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.r2dbc.function.DefaultSqlResult$1.apply(DefaultSqlResult.java:54) ~[spring-data-r2dbc-1.0.0.BUILD-20181030.065337-2.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.r2dbc.function.DefaultSqlResult$1.apply(DefaultSqlResult.java:51) ~[spring-data-r2dbc-1.0.0.BUILD-20181030.065337-2.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient.doInConnectionMany(DefaultDatabaseClient.java:1016) ~[spring-data-r2dbc-1.0.0.BUILD-20181030.065337-2.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient.lambda$inConnectionMany$2(DefaultDatabaseClient.java:160) ~[spring-data-r2dbc-1.0.0.BUILD-20181030.065337-2.jar:1.0.0.BUILD-SNAPSHOT]
`

is this a problem with the current snapshot releases?

Any hint is very welcome :)

**Comment by mp911de** [comment]
Spring Data R2DBC did not catch up with the latest R2DBC SPI changes, therefore `AbstractMethodError` occurs. We need to upgrade and recompile.

**Comment by eiswind** [comment]
Yes, is ok now.
